# Generated by Django 4.2.7 on 2024-01-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'База сотрудников', 'verbose_name_plural': 'База сотрудников'},
        ),
    ]
